module.exports = {
  AUTHORIZATION_CODE: "authorization_code",
  OAUTH_SCOPE: "openid profile email",
  OAUTH_RESPONSE_TYPE_CODE: "code",
  OAUTH_ACCESS_TYPE_OFFLINE: "offline",
  OAUTH_PROMPT_CONSENT: "consent",
  ROLE_USER: "user",
  ROLE_ADMIN: "admin",
  JWT_EXPIRATION_TIME_1HR: "1hr",
  ACCESS_COOKIE_MAX_AGE: 3600 * 1000,
  REFRESH_COOKIE_MAX_AGE: 30 * 24 * 60 * 60 * 1000,
  SAME_SITE_STRICT: "Strict",
  ACCESS_COOKIE_NAME: "BILLEASY_ACCESS_T",
  REFRESH_COOKIE_NAME: "BILLEASY_REFRESH_T",

  ACCESS_COOKIE_EXPIRATION_BUFFER: 60,
  GET_REQUEST: "GET",
};
